[package]
name = "kubewarden-policy-sdk"
description = "Kubewarden Policy SDK for the Rust language"
repository = "https://github.com/kubewarden/policy-sdk-rust"
version = "0.3.2"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2018"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
k8s-openapi = { version = "0.14.0", default-features = false, features = ["v1_22"] }
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
slog = "2.7.0"
wapc-guest = "0.4.0"
serde_yaml = "0.8.23"
url = { version = "2.2.2", features = ["serde"] }

[dev-dependencies]
assert-json-diff = "2.0.1"
